uint8 RESULT_SUCCESS = 0
uint8 RESULT_TIMEOUT = 1
uint8 RESULT_STUCK = 2
uint8 RESULT_ERROR = 3

std_msgs/Header header
string odom_frame

geometry_msgs/Pose2D target

spes_msgs/MoveProperties linear_properties
spes_msgs/MoveProperties angular_properties
bool ignore_obstacles
builtin_interfaces/Duration timeout
uint8 reversing
uint8 mode 7

# TODO
float64 translate_yaw_error_tolerance
---
uint8 result
---