controller_manager:
  ros__parameters:
    update_rate: 50

    diffdrive_controller:
      type: diff_drive_controller/DiffDriveController

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

diffdrive_controller:
  ros__parameters:
    left_wheel_names: ["left_motor"]
    right_wheel_names: ["right_motor"]

    wheel_separation: 0.365
    wheel_radius: 0.0762

    use_stamped_vel: false
    enable_odom_tf: true
    odom_frame_id: odom

    pose_covariance_diagonal:
      [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
    twist_covariance_diagonal:
      [0.1, 0.1, 1000000.0, 1000000.0, 1000000.0, 1000.0]

    linear.x.has_velocity_limits: true
    linear.x.min_velocity: -0.5
    linear.x.max_velocity: 0.5
    linear.x.has_acceleration_limits: true
    linear.x.min_acceleration: -1.0
    linear.x.max_acceleration: 1.0

    angular.z.has_velocity_limits: true
    angular.z.min_velocity: -5.0
    angular.z.max_velocity: 5.0
    angular.z.has_acceleration_limits: true
    angular.z.min_acceleration: -10.0
    angular.z.max_acceleration: 10.0

motion_control_handle:
  ros__parameters:
    end_effector_link: arm_tcp_link
    robot_base_link: arm_base_link
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: arm_tcp_link
    robot_base_link: arm_base_link
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5

    command_interfaces:
      - position

    solver:
      error_scale: 1.0
      iterations: 12

    pd_gains:
      trans_x: { p: 1.0 }
      trans_y: { p: 1.0 }
      trans_z: { p: 1.0 }
      rot_x: { p: 0.5 }
      rot_y: { p: 0.5 }
      rot_z: { p: 0.5 }

joint_state_broadcaster:
  ros__parameters:
    extra_joints:
      - caster_wheel_joint
      - caster_steering_joint
