source /opt/ros/humble/setup.bash
source /${DOCKERUSER}/ros2_ws/install/local_setup.bash
source /${DOCKERUSER}/ros2_libs_ws/install/local_setup.bash
alias cb='colcon build --symlink-install --cmake-args -DCMAKE_BUILD_TYPE=Debug'
export ROS_DOMAIN_ID=101