controller_manager:
  ros__parameters:
    update_rate: 200

    cartesian_motion_controller:
      type: cartesian_motion_controller/CartesianMotionController

    motion_control_handle:
      type: cartesian_controller_handles/MotionControlHandle

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

motion_control_handle:
  ros__parameters:
    end_effector_link: link6
    robot_base_link: link_base
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

cartesian_motion_controller:
  ros__parameters:
    end_effector_link: link6
    robot_base_link: link_base
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6

    command_interfaces:
      - position

    solver:
      error_scale: 1.0
      iterations: 12

    pd_gains:
      trans_x: { p: 1.0 }
      trans_y: { p: 1.0 }
      trans_z: { p: 1.0 }
      rot_x: { p: 0.5 }
      rot_y: { p: 0.5 }
      rot_z: { p: 0.5 }
